### ISSUE TITLE
events: size(batch_size, choice_num, seq_len + 1, 5)

### ISSUE THREAD

**Issue by xiamenwcy** [waltbai/MCPredictor#3]
network.py----> forward 中param events: size(batch_size, choice_num, seq_len + 1, 5)，这里5代表什么意思，choice_num又是什么意思？

**Comment by waltbai** [comment]
> network.py----> forward 中param events: size(batch_size, choice_num, seq_len + 1, 5)，这里5代表什么意思，choice_num又是什么意思？

这里是verb:dep, subj, obj, iobj四个词，若verb和dep分开则为5，这是早期的一种尝试，events的最后一个维度目前是4。choice_num=5，由于当前数据集都是给定5个选项的多选形式。
