### ISSUE TITLE
MCNC dataset Construction Problems

### ISSUE THREAD

**Issue by zfq-hit** [waltbai/MCPredictor#4]
Hi, I am following your great work, and MCNC codebase has too many bugs today, after following your modification, I have tried to fix a lot, but there are still too much, could you share your modified eventchains-aaai folder, I think this may help a lot. I would appreciate it if you could help me !
And what is the purpose of bin/event_pipeline/rich_docs/gigaword.txt, if I need origin text then I need to install it?

**Comment by waltbai** [comment]
> Hi, I am following your great work, and MCNC codebase has too many bugs today, after following your modification, I have tried to fix a lot, but there are still too much, could you share your modified eventchains-aaai folder, I think this may help a lot. I would appreciate it if you could help me ! And what is the purpose of bin/event_pipeline/rich_docs/gigaword.txt, if I need origin text then I need to install it?

If you need this code, I think it is better to send e-mail to ask for it privately, since this code contains many absolute directory about my computing platform. That's very kind of you if you are willing to help me to fix those bugs.
```gigaword.txt``` contains the scripts to generate necessary temp files (such as stop event list) and split dataset. These scripts should run after the event chains are extracted, i.e., after finishing ```pipeline.sh``` stage 1~5.

**Comment by zfq-hit** [comment]
SCPredictor 66.24

**Comment by zfq-hit** [comment]
Thanks for your reply, I have solved the problem of building the dataset because I got help from others, but I would still like to know if SCPredictor=66.24 also used the original sentence in the test, I am not sure which configuration file was used in the test, that equals use_sent is False or True while testing.

**Comment by waltbai** [comment]
> Thanks for your reply, I have solved the problem of building the dataset because I got help from others, but I would still like to know if SCPredictor=66.24 also used the original sentence in the test, I am not sure which configuration file was used in the test, that equals use_sent is False or True while testing.

I would be grateful if you can tell me what's the problem that I missed. 
Training/testing should use the same config file, which means SCPredictor also uses the sentence information in testing. Detailed instructions to train and test are mentioned in README.md Training/Testing part.

**Comment by zfq-hit** [comment]
There are a lot of changes that need to be made, so maybe I'll go over them later and write them down and share them 
抱歉再次打扰，然而我还有最后一个问题是测试集和验证集是如何被挑选出来的，想请问这个文件是如何生成的dev_corp_dir = os.path.join(data_dir, "gigaword-nyt", "eval", "multiple_choice", "dev_10k")，或者我可以用生成训练集的方法生成测试和验证集，之后再随机选择10k条吗？感谢回复！

**Comment by zfq-hit** [comment]
There are a lot of changes that need to be made, so maybe I'll go over them later and write them down and share them

**Comment by zfq-hit** [comment]
> There are a lot of changes that need to be made, so maybe I'll go over them later and write them down and share them

**Comment by zfq-hit** [comment]
There are a lot of changes that need to be made, so maybe I'll go over them later and write them down and share them. Thank you very much!

> I would be grateful if you can tell me what's the problem that I missed. Training/testing should use the same config file, which means SCPredictor also uses the sentence information in testing. Detailed instructions to train and test are mentioned in README.md Training/Testing part.
