### ISSUE TITLE
SCPredictor-s模型复现问题

### ISSUE THREAD

**Issue by zfq-hit** [waltbai/MCPredictor#5]
1.[https://mark.granroth-wilding.co.uk/papers/what_happens_next/](url)
2.[https://github.com/waltbai/MCPredictor/blob/main/experiments/preprocess.py](url)
3.[https://github.com/waltbai/MCPredictor/blob/main/config/scpredictor.json](url)
你好，我在复现论文SCPredictor-s模型时遇到了一些问题，如果方便的话希望能够得到您的帮助。我使用what_happens_next中的代码处理语料库得到了每个文档对应的实体以及事件，然后使用preprocess.py处理得到了包括single_train,single_dev,single_test在内的数据集，以及pretrain_embedding.npy和word_dict.json，然后使用scpredictor.json中的配置训练模型，然而准确率只有55.82，远低于论文中的结果58.28，之后我将batchsize从1000改为了200，准确率提高到了57.72。想请问config文件中的配置是复现论文所需要的配置吗，或者我有什么遗漏导致无法直接复现结果吗？
感谢您的回复！

**Comment by waltbai** [comment]
> 1.[https://mark.granroth-wilding.co.uk/papers/what_happens_next/](url) 2.[https://github.com/waltbai/MCPredictor/blob/main/experiments/preprocess.py](url) 3.[https://github.com/waltbai/MCPredictor/blob/main/config/scpredictor.json](url) 你好，我在复现论文SCPredictor-s模型时遇到了一些问题，如果方便的话希望能够得到您的帮助。我使用what_happens_next中的代码处理语料库得到了每个文档对应的实体以及事件，然后使用preprocess.py处理得到了包括single_train,single_dev,single_test在内的数据集，以及pretrain_embedding.npy和word_dict.json，然后使用scpredictor.json中的配置训练模型，然而准确率只有55.82，远低于论文中的结果58.28，之后我将batchsize从1000改为了200，准确率提高到了57.72。想请问config文件中的配置是复现论文所需要的配置吗，或者我有什么遗漏导致无法直接复现结果吗？ 感谢您的回复！

你好。我觉得问题可能出在lr上。早期scpredictor-s是单独写的模型并且产生了结果，当时采用了一些方法调整lr从而加速训练，比如前期设置较大的lr（scpredictor和mcpredictor都不必使用类似技巧）。你可以使用1e-3的学习率尝试一下，并且多跑一些epoch，我这几天重新跑了一遍scpredictor-s，使用lr=1e-3，在二十多轮左右dev上的准确率已经能够达到58+。如果还想要尝试该模型的极限能力，可以尝试以lr=1e-3跑10~15轮，再以lr=1e-4微调。

**Comment by zfq-hit** [comment]
感谢指导！模型都成功复现出来了
