### ISSUE TITLE
数据集与评测问题

### ISSUE THREAD

**Issue by zhufq00** [waltbai/MCPredictor#6]
您好，很抱歉再次打扰您，然而论文中还有一些模糊的地方想和您确认一下。我重新生成了数据集并成功复现了论文中结果，该数据集的训练集大小为1440285，和论文中的一致，
![1645942866(1)](https://user-images.githubusercontent.com/37504718/155870898-fd112f6a-1868-4438-b53c-926eb7d431ed.png)
但是table 2中的复现结果是使用这个较大的数据集复现出来的吗，还是用的其他数据集？

**Comment by waltbai** [comment]
> 您好，很抱歉再次打扰您，然而论文中还有一些模糊的地方想和您确认一下。我重新生成了数据集并成功复现了论文中结果，该数据集的训练集大小为1440285，和论文中的一致， ![1645942866(1)](https://user-images.githubusercontent.com/37504718/155870898-fd112f6a-1868-4438-b53c-926eb7d431ed.png) 但是table 2中的复现结果是使用这个较大的数据集复现出来的吗，还是用的其他数据集？

第一部分，即打星号的模型是原论文汇报的结果（除PairLSTM使用SGNN论文中汇报的结果）；第二部分为复现结果，其中PairLSTM和SGNN使用原模型训练结果直接预测，因为该结果高于重新训练，PMI、Event-Comp、SAM-Net是使用生成的数据集重新训练的

**Comment by zfq-hit** [comment]
感谢答复！



---原始邮件---
发件人: "Long ***@***.***&gt;
发送时间: 2022年2月27日(周日) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [waltbai/MCPredictor] 数据集与评测问题 (Issue #6)




  
您好，很抱歉再次打扰您，然而论文中还有一些模糊的地方想和您确认一下。我重新生成了数据集并成功复现了论文中结果，该数据集的训练集大小为1440285，和论文中的一致，  但是table 2中的复现结果是使用这个较大的数据集复现出来的吗，还是用的其他数据集？
  
第一部分，即打星号的模型是原论文汇报的结果（除PairLSTM使用SGNN论文中汇报的结果）；第二部分为复现结果，其中PairLSTM和SGNN使用原模型训练结果直接预测，因为该结果高于重新训练，PMI、Event-Comp、SAM-Net是使用生成的数据集重新训练的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
